#############################################################################
# Makefile for building: translator
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  Interface.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Interface.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../include/x86_64-linux-gnu/qt5 -I../../include/x86_64-linux-gnu/qt5/QtWidgets -I../../include/x86_64-linux-gnu/qt5/QtGui -I../../include/x86_64-linux-gnu/qt5/QtCore -I. -I../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = translator1.0.0
DISTDIR = /usr/src/tfg/.tmp/translator1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/interface/main.cpp \
		src/interface/MainWindow.cpp moc_MainWindow.cpp
OBJECTS       = main.o \
		MainWindow.o \
		moc_MainWindow.o
DIST          = ../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Interface.pro src/interface/MainWindow.hpp src/interface/main.cpp \
		src/interface/MainWindow.cpp
QMAKE_TARGET  = translator
DESTDIR       = 
TARGET        = translator


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Interface.pro ../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf ../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		../../lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Interface.pro \
		../../lib/x86_64-linux-gnu/libQt5Widgets.prl \
		../../lib/x86_64-linux-gnu/libQt5Gui.prl \
		../../lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Interface.pro
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
../../lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Interface.pro:
../../lib/x86_64-linux-gnu/libQt5Widgets.prl:
../../lib/x86_64-linux-gnu/libQt5Gui.prl:
../../lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Interface.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/interface/MainWindow.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/interface/main.cpp src/interface/MainWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp
moc_MainWindow.cpp: ../../include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLabel \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlabel.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		src/interface/MainWindow.hpp \
		../../lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/usr/src/tfg -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/local/include/c++/8.2.0 -I/usr/local/include/c++/8.2.0/x86_64-linux-gnu -I/usr/local/include/c++/8.2.0/backward -I/usr/local/lib/gcc/x86_64-linux-gnu/8.2.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux-gnu/8.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/interface/MainWindow.hpp -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/interface/main.cpp src/interface/MainWindow.hpp \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLabel \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlabel.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/interface/main.cpp

MainWindow.o: src/interface/MainWindow.cpp src/interface/MainWindow.hpp \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLabel \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlabel.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		../../include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QGridLayout \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qgridlayout.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlayout.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qlayoutitem.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qboxlayout.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QFileDialog \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qfiledialog.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qdir.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/qfileinfo.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/QGroupBox \
		../../include/x86_64-linux-gnu/qt5/QtWidgets/qgroupbox.h \
		../../include/x86_64-linux-gnu/qt5/QtCore/QProcess \
		../../include/x86_64-linux-gnu/qt5/QtCore/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/interface/MainWindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/translator/bin || mkdir -p $(INSTALL_ROOT)/opt/translator/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/translator/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/translator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/translator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/translator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

